version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: code-heatmap-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-keyfile:/data/keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: >
      bash -c "
        chmod 600 /data/keyfile &&
        mongod --replSet rs0 --bind_ip_all --keyFile /data/keyfile --auth
      "

  mongodb-setup:
    image: mongo:latest
    depends_on:
      - mongodb
    volumes:
      - ./mongodb-keyfile:/data/keyfile
    command: >
      bash -c "
        sleep 10 &&
        mongosh --host mongodb --username admin --password password --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [{ _id: 0, host: \"mongodb:27017\" }]
          });
          db.getSiblingDB(\"admin\").createUser({
            user: \"admin\",
            pwd: \"password\",
            roles: [{ role: \"root\", db: \"admin\" }]
          });
        '
      "
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongodb_data: 